# -*- mode: org; mode: flyspell; ispell-local-dictionary: "en" -*-
#+SETUPFILE: zh-inc.org

* Discrete mathematics 1 - First test[fn:1]
[fn:1]You can use a calculator (but only if it is not
programable). Every problem is worth 10 points, you need 20, 30, 40,
50 points for the grades 2, 3, 4, 5.


1. What is the rectangular form of the following numbers:
   1) $(5-i)(1+7i)$;
   2) $(3-2i)^2$;
   3) $(11-2i)/(-2+3i)$;
   4) $i^{15}$;
   5) $(-1-i)^{10}$.

2. Using the polar form, calculate the polar and rectangular form of
   $z$, then find all the complex $w$ values, so that $w^4=z$.

   \[ z = \frac{(-1-i)^{16}}{(\sqrt{3}-i)^{7}} \]

3. For each of the following conditions, give two complex numbers
   which satisfy them (remember, two numbers for each):
   1) $z^5 = |z|$.
   2) $z = 1/\overline{z}$.
   3) $\operatorname{Re}(z)=2\operatorname{Im}(z)$.
   4) $|iz| = |-z^3|$.
   5) $|z +3 -i| = |z -4|$.

4. In a fictional universe, we use the following predivates: 
   $S(x): x$ is a sorcerer, 
   $W(x): x$ is a witch, 
   $M(x): x$ is a muggle, 
   $F(x): x$ female, 
   $A(x): x$ animal, 
   $H(x): x$ human, 
   $P(x,y): x$ is the patronus of $y$,
   $C(x,y): x$ is the child of $y$. 
   So $P(stag, Harry)$ means that Harry's patronus is stag.
   Express the following sentences using logical formulas:
   1) Ron's patronus is terrier.
   2) Every sorcerer has a parent.
   3) Every muggle is a human, but not all humans are muggles.
   4) There is at least on muggle, with one human parent and one
      sorcerer parent.
   5) Sorcerers, witches patronuses are animals.
 
5. Let $A = \{2, 3, 5, 7\}$, $B = \{1, 2, 3, 4\}$.  Calculate $A\Delta
   B$. Give three-three different $C$ sets, for each of the following
   statements are true separately:
   1) $A \cap C \subseteq B$.
   2) $\{1, 2\} \subseteq A \Delta C \subseteq B$.
   3) $A\cup (B \cap C) = (A\cup B) \cap C$.


6. You can choose from the following two problems.

   6S: Under exactly which conditions is it true that $A \Delta B
   \subseteq A$? Prove your statement!  Which are the sets $A$, for
   which there exists a set $B$ so that $A \Delta B = A \cap B$?
   Explain your answer.

   6R: For the following $R$ and $S$ relation, decide if they are
   reflexive, symmetric, transitive and anti-symmetric on the sets $X$
   (for $R$) and $Y$ (for $S$), and give $R\circ S$ and $S\circ R$ as a
   set of order pairs:
   - $R = \{(1, 2), (2, 1), (3, 4), (4,3), (2, 2), (4, 4), (5,5)\}$,
     $X = \{1, 2, 3, 4, 5\}$.
   - $S = \{(x, y) \mid x, y\in \mathbb{N}, |x-y| \leq 2\}$, $Y =
     \mathbb{N}$.


