# -*- mode: org; mode: flyspell; ispell-local-dictionary: "hu" -*-
#+SETUPFILE: zh-inc.org
#+TITLE:
#+AUTHOR:
#+DATE:

* Diszkrét matematika 2. - Első zárthelyi dolgozat - Név/NK: 
1. Van e olyan 8 szög\-pontú egyszerű gráf, melyben a csúcsok foka rendre:
   #+ATTR_LATEX: :environment inparaenum
   1) $7,7,5,5,4,2,2,0$;
   2) $6,6,5,4,4,2,1,1$;
   3) $6,6,5,3,2,2,1,1$;
   4) $7,4,3,2,2,2,1,1$.

2. Hány pontja van egy gráfnak, ha az éleinek száma pontosan
   tizenkettede a komplementerének élszámának?  Síkba\-rajzolható e ez
   a gráf?

3. Legyenek a $G$ gráfnak a csucsai az $n$ hosszú 0-1 sorozatok, és
   legyen összekötve két csúcs, ha legalább két koordinátában
   különböznek. Milyen $n$ eseten van a gráfban zárt Euler--vonal
   illetve, Hamilton--kör?

4. Jelölje $D_{20}$ a szabályos 10-szög egybevágó leképezéseit ahol a
   $\varphi$ az óramutató forgásának irányával ellenkező, $2\pi/10$
   radiánnal való elforgatást, $\tau$ pedig a függőleges szimmetria
   tengelyre való tükrözést jelöli.  Vizsgáljuk meg a $(D_{10},\circ)$
   diéder\-csoportot: Legyen $g_1=\tau \circ \varphi^3 \circ \tau^3
   \circ \varphi^5$ és $g_2=\varphi^6\circ \tau \circ \varphi^7$.
   #+ATTR_LATEX: :environment inparaenum
   1) Soroljuk fel $D_{15}$ elemeit $\varphi$ és $\tau$ segítségével
   2) Egyszerűssítsük $g_1$ és $g_2$ elemet!
   3) Mi $g_1$, $g_2$ illetve $g_1 \circ g_2$ rendje.
   4) Soroljuk fel $\langle g_1 \rangle$, $\langle g_1 \rangle$ és
      $\langle g_1, g_1 \rangle$.

5. Legyen $\mathbb{L}=\{\uparrow,\downarrow\}$, ahol $\uparrow$ az
   igazat, és $\downarrow$ pedig a hamist jelenti. Igaz e, hogy
   $(\mathbb{L},\otimes)$ grupoid, fél\-csoport, monoid illetve csoport?
   Igaz e hogy kommutatív?

6. Bizonyítsuk be, hogy ha $(G,\cdot)$ véges csoport, akkor minden
   $a\in G$ -re $a^{|G|}=e$, ahol $e$ a csoport egység\-eleme.
\vfill
* Diszkrét matematika 2. - Első zárthelyi dolgozat - Név/NK: 
1. Van e olyan 8 szög\-pontú egyszerű gráf, melyben a csúcsok foka rendre:
   #+ATTR_LATEX: :environment inparaenum
   1) $7,7,5,5,4,2,2,0$;
   2) $6,6,5,4,4,2,1,1$;
   3) $6,6,5,3,2,2,1,1$;
   4) $7,4,3,2,2,2,1,1$.

2. Hány pontja van egy gráfnak, ha az éleinek száma pontosan
   tizenkettede a komplementerének élszámának?  Síkba\-rajzolható e ez
   a gráf?

3. Legyenek a $G$ gráfnak a csucsai az $n$ hosszú 0-1 sorozatok, és
   legyen összekötve két csúcs, ha legalább két koordinátában
   különböznek. Milyen $n$ eseten van a gráfban zárt Euler--vonal
   illetve, Hamilton--kör?

4. Jelölje $D_{20}$ a szabályos 10-szög egybevágó leképezéseit ahol a
   $\varphi$ az óramutató forgásának irányával ellenkező, $2\pi/10$
   radiánnal való elforgatást, $\tau$ pedig a függőleges szimmetria
   tengelyre való tükrözést jelöli.  Vizsgáljuk meg a $(D_{10},\circ)$
   diéder\-csoportot: Legyen $g_1=\tau \circ \varphi^3 \circ \tau^3
   \circ \varphi^5$ és $g_2=\varphi^6\circ \tau \circ \varphi^7$.
   #+ATTR_LATEX: :environment inparaenum
   1) Soroljuk fel $D_{15}$ elemeit $\varphi$ és $\tau$ segítségével
   2) Egyszerűssítsük $g_1$ és $g_2$ elemet!
   3) Mi $g_1$, $g_2$ illetve $g_1 \circ g_2$ rendje.
   4) Soroljuk fel $\langle g_1 \rangle$, $\langle g_1 \rangle$ és
      $\langle g_1, g_1 \rangle$.

5. Legyen $\mathbb{L}=\{\uparrow,\downarrow\}$, ahol $\uparrow$ az
   igazat, és $\downarrow$ pedig a hamist jelenti. Igaz e, hogy
   $(\mathbb{L},\otimes)$ grupoid, fél\-csoport, monoid illetve csoport?
   Igaz e hogy kommutatív?

6. Bizonyítsuk be, hogy ha $(G,\cdot)$ véges csoport, akkor minden
   $a\in G$ -re $a^{|G|}=e$, ahol $e$ a csoport egység\-eleme.
