# -*- mode: org; mode: flyspell; ispell-local-dictionary: "hu"; -*-
#+SETUPFILE: zh-inc.org

#+TITLE: 
#+AUTHOR: 
#+DATE: 

* Diszkrét matematika 2 - 2. ZH, Minta ZH
  1. Határozzuk meg \(a\)-t és \(b\)-t úgy, hogy \(x^4 + 3x^2 +ax+b\)
     osztható legyen \(x^2 - 2ax + 2\)-vel \(\mathbb{Z}, \mathbb{Q},
     \mathbb{R}\), illetve \(\mathbb{C}\) felett.
  2. Keressük meg a \(x^6 - 6x^4 - 4x^3 + 9x^2 + 12x + 4\mathbb{Q}[x]\)
     polinom többszörös gyökeit és adjuk meg mindegyiknek a
     multiplicitását.
  3. Határozzuk meg a \(x^4 + x^3 - 3x^2 - 4x - 1\) és \(x^3 + x^2 -
     x - 1\) polinomok legnagyobb közös osztóját
     \(\mathbb{Z}_5[x]\)-ben!
  4. Az kódokról döntsük el, hogy melyik felbontható, prefix, vesszős,
     illetve egyenletes. Rajzoljuk fel a kód\-fát is.
     1) =0, 10, 110, 1110, 1011, 1101=;
     2) =1, 011, 010, 001, 000, 110=;
     3) =0, 10, 110, 1110, 11110, 111110=.
  5. A $0,34; 0,18; 0,17; 0,16; 0,15$ eloszlásokhoz határozzuk meg a
     bináris illetve ternáris Huffman--kódot. Hasonlítsuk össze az
     átlagos kód\-hosszat az entrópiával.
  6. Legyen egy \(\mathbb{F}_2\) feletti lineáris kód generátor\-mátrixa
     \[ \begin{pmatrix} 1 & 0 & 0\\ 0 & 1 & 0\\ 1 & 1 & 0\\ 0 & 1 &
     1\\ 1 & 1 & 1\\ 1 & 0 & 1 \end{pmatrix} \] Adjon meg egy olyan
     generátor\-mátrixot, amelyhez ugyanez a kód\-tér tartozik, de a
     mátrixának első három sora egység\-mátrix. Adja meg a kód egy
     ellenőrző mátrixát. Milyen kód\-szó felel meg az ~110~ üzenetnek?
     Mi a ~101101~ üzenet szindrómája, hogyan kell dekódolni?

