# -*- mode: org; mode: flyspell; -*-
#+SETUPFILE: zh-inc.org

* Discrete mathematics 1 - Second test
  You can use a calculator (but only if it is not programable). Every
  problem is worth 10 points, you need 20, 30, 40, 50 points for the
  grades 2, 3, 4, 5.
  1. 
     1) How many ways can you decorate a Christmas tree with 42 branches
	and 35 decorations (each unique \ie different) if you can put at
	most one decoration on every branch?
     2) How many ways can you decorate a Christmas tree with 52 branches
	and 45 decorations (all the same) if you can put at most one
	decoration on every branch?
     3) Santa is filling his bag with Christmas gifts! There are 72
        kinds of gifts, how many ways can he fill his bag with 100
        gifts (the order he puts the gifts in doesn't matter)?
     4) How many ways can Santa give 25 different presents to 15
        children (some of the kids might have been bad \ie they might
        not get a present)?
  2. 
     1) How many ways can Santa put 16 (different) presents into 4
        stockings if he has to put the same number of presents into
        each?
     2) How many ways can Santa put 16 (of the same) presents into 4
        stockings if he has to put at least two presents into each?
     3) How many ways can we wrap 15 presents, if we want 3 to be
        wrapped in red, 5 in gold and 7 in blue wrapping paper?
     4) How many ways can we choose 12 cards from a deck of 52 cards, so
	that we chose at lease 3 aces (there are 4 aces in the deck)?
  3. How many 6 digit numbers can you make with the digits
     1,2,3,4,5,6,7,8 which :
     #+ATTR_LATEX: :environment inparaenum
     1) are divisible by 4;
     2) start with an even number;
     3) the start with a digit smaller then the double of the last digit;
     4) consists of only prime digits?

  4. Solve the following three Diophantine equations (separately):
     #+ATTR_LATEX: :environment inparaenum
     1) $82x \equiv 6 \pmod {172}$; 
     2) $89x \equiv 3 \pmod {40}$;
     3) $45x \equiv 12 \pmod {20}$;
  5. What is $2021^{2016} \bmod 100$?

  6. Solve the following system of congruences: $3x \equiv 1 \pmod4, 5x
     \equiv 3 \pmod7, 7x \equiv 2 \pmod9$.
